### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by ukusormus** [ukusormus/response-machine#5]
make it easier to deploy, auto-restart etc.

**Comment by ParthM01** [comment]
hey, i have created a dockerfile to run the python scripts can u assign me so that i can merge the  dockerfile into ur git .

Thanks!

**Comment by ukusormus** [comment]
sure, we can try, assigning.

just for context, i haven't really thought about this (pet) project taking PR-s (yet).
i have had some some local tests with docker and docker compose that would also require rewriting parts of the main backend python file, e.g. have an option to use env vars
